import { module1Lessons } from './module1-variables';
import { module2Lessons } from './module2-operators';
import { module3Lessons } from './module3-control-flow';
import { module4Lessons } from './module4-functions';
import type { SeedLesson } from './module1-variables';

interface SeedModule {
  slug: string;
  title: string;
  description: string;
  sortOrder: number;
}

const modules: SeedModule[] = [
  {
    slug: 'variables-data-types',
    title: 'Variables & Data Types',
    description: 'Store values, understand Python\u2019s core types, and convert between them.',
    sortOrder: 1,
  },
  {
    slug: 'operators',
    title: 'Operators',
    description: 'Do math, compare values, and combine conditions.',
    sortOrder: 2,
  },
  {
    slug: 'control-flow-loops',
    title: 'Control Flow & Loops',
    description: 'Branch your code with if/else and repeat it with loops.',
    sortOrder: 3,
  },
  {
    slug: 'functions',
    title: 'Functions',
    description: 'Package reusable logic and pass information in and out of it.',
    sortOrder: 4,
  },
];

const allLessons: SeedLesson[] = [
  ...module1Lessons,
  ...module2Lessons,
  ...module3Lessons,
  ...module4Lessons,
];

/** Escapes single quotes for safe inclusion in a SQL string literal. */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function buildSql(): string {
  const lines: string[] = [
    '-- =============================================================================',
    '-- Seed data: Python Fundamentals (4 modules, 14 lessons)',
    '-- =============================================================================',
    '-- AUTO-GENERATED by supabase/seed/generate-seed-sql.ts — do not hand-edit.',
    '-- Regenerate with: npx tsx supabase/seed/generate-seed-sql.ts > supabase/seed/seed.sql',
    '-- Run this in your Supabase project\'s SQL Editor AFTER both migrations',
    '-- (000_profiles.sql, 001_lesson_schema.sql) have already been applied.',
    '-- Safe to re-run: modules/lessons are upserted by slug, not duplicated.',
    '-- =============================================================================',
    '',
  ];

  for (const mod of modules) {
    lines.push(
      `insert into public.modules (slug, title, description, sort_order)`,
      `values (${sqlString(mod.slug)}, ${sqlString(mod.title)}, ${sqlString(mod.description)}, ${mod.sortOrder})`,
      `on conflict (slug) do update set`,
      `  title = excluded.title,`,
      `  description = excluded.description,`,
      `  sort_order = excluded.sort_order;`,
      ''
    );
  }

  for (const lesson of allLessons) {
    const contentJson = sqlString(JSON.stringify(lesson.content));
    lines.push(
      `insert into public.lessons (module_id, slug, title, summary, sort_order, estimated_minutes, xp_reward, content)`,
      `select id, ${sqlString(lesson.slug)}, ${sqlString(lesson.title)}, ${sqlString(lesson.summary)}, ${lesson.sortOrder}, ${lesson.estimatedMinutes}, ${lesson.xpReward}, ${contentJson}::jsonb`,
      `from public.modules where slug = ${sqlString(lesson.moduleSlug)}`,
      `on conflict (slug) do update set`,
      `  title = excluded.title,`,
      `  summary = excluded.summary,`,
      `  sort_order = excluded.sort_order,`,
      `  estimated_minutes = excluded.estimated_minutes,`,
      `  xp_reward = excluded.xp_reward,`,
      `  content = excluded.content;`,
      ''
    );
  }

  return lines.join('\n');
}

// eslint-disable-next-line no-console -- this script's entire purpose is to print SQL to stdout.
console.log(buildSql());
